version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  
    networks:
      - app-network

  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    container_name: python-server
    env_file:
      - .env
    ports:
      - "${PYTHON_PORT}:${PYTHON_PORT}"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  websocket-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    container_name: websocket-server
    env_file:
      - .env
    ports:
      - "${WS_PORT}:${WS_PORT}"
    depends_on:
      - rabbitmq
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
